#!/usr/bin/env python3“””medical_extractor.py

Lightweight medical guideline extractor (MVP).

• Heuristics to find recommendation sections and extract recommendations as structured JSON.

• Emits ontology_lookup metadata warning when ontology credentials are not configured.

• Embedding provider chosen from EMBEDDING_PROVIDER env var.

This is intentionally conservative and requires human clinician review of all outputs.“””import reimport jsonfrom pathlib import Pathfrom typing import List, Dict, Anyimport datetimeimport os

EMBEDDING_PROVIDER = os.environ.get(“EMBEDDING_PROVIDER”, “openai”)  # configurable by user

RECOMM_SECTION_KEYWORDS = [r”\brecommendation\b”, r”\brecommendations\b”, r”\bgrade\b”, r”\blevel of evidence\b”,r”\bwe recommend\b”, r”\bis recommended\b”, r”\bshould\b”, r”\bcontraindicat”, r”\balgorithm\b”,]

def find_sections(text: str) -> List[Dict[str, Any]]:# Very light heuristic: split on headings (lines with ALL CAPS or starting with “Recommendation”, “Algorithm”, “GRADE”)lines = text.splitlines()sections = []cur = {“title”: “preface”, “text”: []}for ln in lines:if re.match(r’^\s*(?:RECOMMENDATION|RECOMMENDATIONS|ALGORITHM|GRADE|Recommendation|Recommendations)\b’, ln, re.I) or len(ln.strip()) < 200 and ln.strip().endswith(”:”) and len(ln.strip().split()) <= 6:# start new sectionif cur[“text”]:sections.append(cur)cur = {“title”: ln.strip()[:120], “text”: []}continuecur[“text”].append(ln)if cur[“text”]:sections.append(cur)return [{“title”: s[“title”], “text”: “\n”.join(s[“text”])} for s in sections]

def extract_recommendations_from_section(title: str, text: str, source_path: str = None) -> List[Dict[str, Any]]:recs = []# heuristics: lines that start with “Recommendation”, “We recommend”, “Grade”, or numerically listed lines “1. “for match in re.finditer(r’(?im)^(?:\s*(?:\d+.\s+)?(Recommendation[s]?:|We recommend|Recommend|Grade[:\s]|Strong recommendation|Conditional recommendation|Should))(.{10,800})’, text):snippet = match.group(0).strip()rec = {“id”: None,“text”: snippet,“population”: None,“intervention”: None,“comparator”: None,“outcome”: None,“conditions_of_application”: None,“contraindications”: None,“strength”: None,  # GRADE-like (Strong/Conditional/Unspecified)“level_of_evidence”: None,  # narrative if found“references”: [],“provenance”: {“source”: source_path or “unknown”, “extracted_at”: datetime.datetime.utcnow().isoformat()},“confidence”: None,“requires_human_review”: True,}# try to parse simple GRADE markersif re.search(r’\bstrong\b’, snippet, re.I):rec[“strength”] = “strong”elif re.search(r’\bconditional\b|\bweak\b’, snippet, re.I):rec[“strength”] = “conditional”else:rec[“strength”] = “unspecified”# find parenthetical references like (1), (Smith 2020)refs = re.findall(r’([^)]+\d{4}[^)])|[\d+]’, snippet)rec[“references”] = refs# simple PICO parse (very heuristic)pop = re.search(r’for (patients|people|adults|children|infants|pregnant)\b[^.,;:\n]{0,80}’, snippet, re.I)if pop:rec[“population”] = pop.group(0)# capture contraindication lines nearbycontra = re.search(r’(contraindicat[^.\n]|do not use[^.\n]*)’, text, re.I)if contra:rec[“contraindications”] = contra.group(0)[:400]# just keep a short justification snippetjust = snippet[:300]rec[“provenance”][“justifying_snippet”] = justrecs.append(rec)# fallback: search for lines with “should” that look prescriptiveif not recs:for ln in text.splitlines():if re.search(r’\bshould\b’, ln, re.I) and len(ln.strip()) > 20:recs.append({“id”: None,“text”: ln.strip(),“population”: None,“intervention”: None,“comparator”: None,“outcome”: None,“conditions_of_application”: None,“contraindications”: None,“strength”: “unspecified”,“level_of_evidence”: None,“references”: [],“provenance”: {“source”: source_path or “unknown”, “justifying_snippet”: ln.strip()[:300]},“confidence”: None,“requires_human_review”: True,})return recs

def extract_from_file(path: str) -> Dict[str, Any]:p = Path(path)text = p.read_text(encoding=“utf-8”, errors=“ignore”)sections = find_sections(text)recommendations = []for sec in sections:# only process sections likely to contain recommendationsif any(re.search(k, sec[“title”] + “ “ + sec[“text”], re.I) for k in RECOMM_SECTION_KEYWORDS):recs = extract_recommendations_from_section(sec[“title”], sec[“text”], source_path=str(p))for r in recs:r[“id”] = f”rec-{len(recommendations)+1:03d}”recommendations.append(r)# fallback: if none found, attempt a broader scanif not recommendations:recommendations = extract_recommendations_from_section(“full_text”, text, source_path=str(p))for i, r in enumerate(recommendations, start=1):r[“id”] = f”rec-{i:03d}”out = {“source”: str(p),“extracted_at”: datetime.datetime.utcnow().isoformat(),“embedding_provider”: EMBEDDING_PROVIDER,“recommendations”: recommendations,“ontology_lookup”: {“status”: “skipped”,“note”: “UMLS/SNOMED mapping disabled by default — set up credentials to enable”,“warning”: “ontology_lookup_requires_credentials”,}}return out

def extract_from_text(text: str, source_label: str = “inline”) -> Dict[str, Any]:sections = find_sections(text)recommendations = []for sec in sections:if any(re.search(k, sec[“title”] + “ “ + sec[“text”], re.I) for k in RECOMM_SECTION_KEYWORDS):recs = extract_recommendations_from_section(sec[“title”], sec[“text”], source_path=source_label)for r in recs:r[“id”] = f”rec-{len(recommendations)+1:03d}”recommendations.append(r)if not recommendations:recommendations = extract_recommendations_from_section(“full_text”, text, source_label)for i, r in enumerate(recommendations, start=1):r[“id”] = f”rec-{i:03d}”return {“source”: source_label,“extracted_at”: datetime.datetime.utcnow().isoformat(),“embedding_provider”: EMBEDDING_PROVIDER,“recommendations”: recommendations,“ontology_lookup”: {“status”: “skipped”,“note”: “UMLS/SNOMED mapping disabled by default — set up credentials to enable”,“warning”: “ontology_lookup_requires_credentials”,}}

if name == “main”:import sys, argparseparser = argparse.ArgumentParser()parser.add_argument(“input”, help=“file or - for stdin”)args = parser.parse_args()if args.input == “-”:text = sys.stdin.read()out = extract_from_text(text, source_label=“stdin”)else:out = extract_from_file(args.input)print(json.dumps(out, indent=2, ensure_ascii=False))